import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { supabase } from './lib/supabase'

type RecordItem = Record<string, any>
const displayDate = (value?: string) => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'Not scheduled'

function Shell({ title, children }: { title: string; children: ReactNode }) {
  return <section className="dashboard"><header className="dashboard-header"><div><p className="eyebrow">Secure portal</p><h1>{title}</h1><p>Information is visible only to the account associated with this portal.</p></div><button className="text-button" onClick={async () => { await supabase?.auth.signOut(); location.hash = '#/portal' }}>Sign out</button></header>{children}</section>
}
function Notice({ children }: { children: ReactNode }) { return <p className="dashboard-message">{children}</p> }
function List({ title, items, render }: { title: string; items: RecordItem[]; render: (item: RecordItem) => ReactNode }) { return <section className="portal-panel"><h2>{title}</h2>{items.length ? <div className="portal-list">{items.map(render)}</div> : <p className="empty-state">Nothing has been added yet.</p>}</section> }

export function ParentDashboard() {
  const [data, setData] = useState<RecordItem>({ students: [], sessions: [], assignments: [], progress: [] }); const [error, setError] = useState('')
  useEffect(() => { void (async () => { if (!supabase) return setError('Portal access is not configured.'); const [profile, students, sessions, assignments, progress] = await Promise.all([supabase.from('parents').select('first_name,last_name').maybeSingle(), supabase.from('students').select('id,first_name,last_name,grade,current_course').order('first_name'), supabase.from('tutoring_sessions').select('id,starts_at,ends_at,status,meeting_url,students(first_name,last_name),tutors(first_name,last_name)').order('starts_at'), supabase.from('assignments').select('id,title,instructions,due_at,status,students(first_name,last_name)').order('due_at'), supabase.from('student_progress').select('id,area,mastery_level,notes,recorded_at,students(first_name,last_name)').order('recorded_at', { ascending: false })]); const failed = [profile, students, sessions, assignments, progress].find(result => result.error); if (failed?.error) return setError('We could not load this portal. Please try again.'); setData({ profile: profile.data, students: students.data || [], sessions: sessions.data || [], assignments: assignments.data || [], progress: progress.data || [] }) })() }, [])
  return <Shell title={`Parent Dashboard${data.profile ? ` — ${data.profile.first_name}` : ''}`}>{error && <Notice>{error}</Notice>}<div className="portal-grid"><List title="Students" items={data.students} render={student => <article key={student.id}><b>{student.first_name} {student.last_name}</b><span>{student.grade || 'Grade not listed'} · {student.current_course || 'Current subject not listed'}</span></article>} /><List title="Upcoming sessions" items={data.sessions} render={session => <article key={session.id}><b>{displayDate(session.starts_at)}</b><span>{session.students?.first_name} {session.students?.last_name} · {session.status}</span>{session.meeting_url && <a href={session.meeting_url} target="_blank" rel="noreferrer">Join online session</a>}</article>} /><List title="Assignments" items={data.assignments} render={assignment => <article key={assignment.id}><b>{assignment.title}</b><span>{assignment.students?.first_name} {assignment.students?.last_name} · {assignment.status}</span><small>{assignment.instructions || 'No additional instructions.'}</small></article>} /><List title="Progress updates" items={data.progress} render={entry => <article key={entry.id}><b>{entry.area}</b><span>{entry.students?.first_name} {entry.students?.last_name} · Mastery {entry.mastery_level || '—'}/5</span><small>{entry.notes || 'No notes provided.'}</small></article>} /></div></Shell>
}

export function StudentDashboard() {
  const [data, setData] = useState<RecordItem>({ sessions: [], assignments: [], progress: [] }); const [error, setError] = useState('')
  useEffect(() => { void (async () => { if (!supabase) return setError('Portal access is not configured.'); const [student, sessions, assignments, progress] = await Promise.all([supabase.from('students').select('first_name,last_name,grade,current_course').maybeSingle(), supabase.from('tutoring_sessions').select('id,starts_at,status,meeting_url,tutors(first_name,last_name)').order('starts_at'), supabase.from('assignments').select('id,title,instructions,due_at,status').order('due_at'), supabase.from('student_progress').select('id,area,mastery_level,notes,recorded_at').order('recorded_at', { ascending: false })]); const failed = [student, sessions, assignments, progress].find(result => result.error); if (failed?.error) return setError('We could not load this portal. Please try again.'); setData({ student: student.data, sessions: sessions.data || [], assignments: assignments.data || [], progress: progress.data || [] }) })() }, [])
  return <Shell title={`Student Dashboard${data.student ? ` — ${data.student.first_name}` : ''}`}>{error && <Notice>{error}</Notice>}<div className="portal-grid"><List title="Sessions" items={data.sessions} render={session => <article key={session.id}><b>{displayDate(session.starts_at)}</b><span>{session.tutors?.first_name} {session.tutors?.last_name} · {session.status}</span>{session.meeting_url && <a href={session.meeting_url} target="_blank" rel="noreferrer">Join online session</a>}</article>} /><List title="Assignments" items={data.assignments} render={assignment => <article key={assignment.id}><b>{assignment.title}</b><span>{assignment.status} · {assignment.due_at ? `Due ${displayDate(assignment.due_at)}` : 'No due date'}</span><small>{assignment.instructions || 'No additional instructions.'}</small></article>} /><List title="Progress" items={data.progress} render={entry => <article key={entry.id}><b>{entry.area}</b><span>Mastery {entry.mastery_level || '—'}/5</span><small>{entry.notes || 'No notes provided.'}</small></article>} /></div></Shell>
}

export function TutorDashboard() {
  const [data, setData] = useState<RecordItem>({ sessions: [], assignments: [], progress: [] }); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [assignment, setAssignment] = useState({ student_id: '', title: '', instructions: '', due_at: '' }); const [progress, setProgress] = useState({ student_id: '', area: '', mastery_level: '3', notes: '' }); const [note, setNote] = useState({ session_id: '', content: '', parent_summary: '' })
  const students = useMemo(() => Array.from(new Map(data.sessions.map((session: RecordItem) => [session.student_id, session.students])).entries()).map(([id, student]) => ({ id, ...(student as RecordItem) })), [data.sessions])
  async function load() { if (!supabase) return setError('Portal access is not configured.'); const [tutor, sessions, assignments, progress] = await Promise.all([supabase.from('tutors').select('id,first_name,last_name').maybeSingle(), supabase.from('tutoring_sessions').select('id,student_id,starts_at,status,meeting_url,students(first_name,last_name)').order('starts_at'), supabase.from('assignments').select('id,title,instructions,due_at,status,students(first_name,last_name)').order('created_at', { ascending: false }), supabase.from('student_progress').select('id,area,mastery_level,notes,recorded_at,students(first_name,last_name)').order('recorded_at', { ascending: false })]); const failed = [tutor, sessions, assignments, progress].find(result => result.error); if (failed?.error) return setError('We could not load this portal. Please try again.'); setData({ tutor: tutor.data, sessions: sessions.data || [], assignments: assignments.data || [], progress: progress.data || [] }) }
  useEffect(() => { void load() }, [])
  async function submit(kind: 'assignment' | 'progress' | 'note', event: FormEvent) { event.preventDefault(); if (!supabase || !data.tutor) return; setError(''); const payload = kind === 'assignment' ? { ...assignment, tutor_id: data.tutor.id, due_at: assignment.due_at || null } : kind === 'progress' ? { ...progress, tutor_id: data.tutor.id, mastery_level: Number(progress.mastery_level) } : { ...note, tutor_id: data.tutor.id, parent_summary: note.parent_summary || null }; const { error: saveError } = await supabase.from(kind === 'note' ? 'session_notes' : kind === 'progress' ? 'student_progress' : 'assignments').insert(payload); if (saveError) return setError(saveError.message); setMessage(`${kind === 'note' ? 'Session note' : kind[0].toUpperCase() + kind.slice(1)} saved.`); if (kind === 'assignment') setAssignment({ student_id: '', title: '', instructions: '', due_at: '' }); if (kind === 'progress') setProgress({ student_id: '', area: '', mastery_level: '3', notes: '' }); if (kind === 'note') setNote({ session_id: '', content: '', parent_summary: '' }); await load() }
  return <Shell title={`Tutor Dashboard${data.tutor ? ` — ${data.tutor.first_name}` : ''}`}>{error && <Notice>{error}</Notice>}{message && <Notice>{message}</Notice>}<div className="portal-grid"><List title="Sessions" items={data.sessions} render={session => <article key={session.id}><b>{displayDate(session.starts_at)}</b><span>{session.students?.first_name} {session.students?.last_name} · {session.status}</span>{session.meeting_url && <a href={session.meeting_url} target="_blank" rel="noreferrer">Meeting link</a>}</article>} /><List title="Assignments" items={data.assignments} render={item => <article key={item.id}><b>{item.title}</b><span>{item.students?.first_name} {item.students?.last_name} · {item.status}</span></article>} /></div><div className="tutor-tools"><ToolForm title="Add assignment" onSubmit={event => submit('assignment', event)}><StudentSelect students={students} value={assignment.student_id} onChange={value => setAssignment({ ...assignment, student_id: value })}/><input required placeholder="Assignment title" value={assignment.title} onChange={e => setAssignment({ ...assignment, title: e.target.value })}/><textarea placeholder="Instructions" value={assignment.instructions} onChange={e => setAssignment({ ...assignment, instructions: e.target.value })}/><input type="datetime-local" value={assignment.due_at} onChange={e => setAssignment({ ...assignment, due_at: e.target.value })}/></ToolForm><ToolForm title="Record progress" onSubmit={event => submit('progress', event)}><StudentSelect students={students} value={progress.student_id} onChange={value => setProgress({ ...progress, student_id: value })}/><input required placeholder="Area of study" value={progress.area} onChange={e => setProgress({ ...progress, area: e.target.value })}/><select value={progress.mastery_level} onChange={e => setProgress({ ...progress, mastery_level: e.target.value })}>{[1,2,3,4,5].map(value => <option key={value} value={value}>Mastery {value}/5</option>)}</select><textarea placeholder="Progress notes" value={progress.notes} onChange={e => setProgress({ ...progress, notes: e.target.value })}/></ToolForm><ToolForm title="Add session note" onSubmit={event => submit('note', event)}><select required value={note.session_id} onChange={e => setNote({ ...note, session_id: e.target.value })}><option value="">Select a session</option>{data.sessions.map((session: RecordItem) => <option key={session.id} value={session.id}>{session.students?.first_name} {session.students?.last_name} — {displayDate(session.starts_at)}</option>)}</select><textarea required placeholder="Private tutoring note" value={note.content} onChange={e => setNote({ ...note, content: e.target.value })}/><textarea placeholder="Optional parent summary" value={note.parent_summary} onChange={e => setNote({ ...note, parent_summary: e.target.value })}/></ToolForm></div></Shell>
}
function ToolForm({ title, onSubmit, children }: { title: string; onSubmit: (event: FormEvent) => void; children: ReactNode }) { return <form className="portal-panel tool-form" onSubmit={onSubmit}><h2>{title}</h2>{children}<button className="button">Save</button></form> }
function StudentSelect({ students, value, onChange }: { students: RecordItem[]; value: string; onChange: (value: string) => void }) { return <select required value={value} onChange={e => onChange(e.target.value)}><option value="">Select a student</option>{students.map(student => <option key={student.id} value={student.id}>{student.first_name} {student.last_name}</option>)}</select> }
